FROM zolex/grpc-php-server:0.0.2

SHELL ["/bin/ash", "-eo", "pipefail", "-c"]

# hadolint ignore=DL3018
RUN apk add --no-cache \
    file \
    gettext \
    git

ARG APCU_VERSION="5.1.19"

# hadolint ignore=DL3018,SC2086
RUN apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        icu-dev \
        libzip-dev \
        mysql-dev \
        zlib-dev \
        libxml2-dev \
    && docker-php-ext-configure zip \
    && docker-php-ext-install -j"$(nproc)" \
        intl \
        pdo_mysql \
        zip \
        sockets \
    && pecl install \
        apcu-${APCU_VERSION} \
    && pecl clear-cache \
    && docker-php-ext-enable \
        apcu \
        opcache \
        sockets \
    && apk del .build-deps \
    && runDeps="$( \
        scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
        | tr ',' '\n' \
        | sort -u \
        | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
        )" \
    && apk add --no-cache --virtual .run-deps $runDeps

COPY ./.env /var/www/.env
COPY ./.rr.yaml /var/www/.rr.yaml
COPY ./bin/console /var/www/bin/console
COPY ./composer.json /var/www/composer.json
COPY ./composer.lock /var/www/composer.lock
COPY ./grpc-php /var/www/grpc-php
COPY ./migrations /var/www/migrations
COPY ./proto /var/www/proto
COPY ./symfony.lock /var/www/symfony.lock
COPY ./src /var/www/src
COPY ./config /var/www/config
RUN cd /var/www && composer install
