version: "2.7"

server:
  command: "vendor/bin/grpc-worker"

grpc:
  # GRPC address to listen
  #
  # This option is required
  listen: "tcp://0.0.0.0:3886"

  # Proto files to use [Multiply files since RR v2.6.0]
  #
  # This option is required. At least one proto file must be specified.
  proto:
    - "proto/services.proto"

  # After having pinged for keepalive check, the server waits for a duration
  # of Timeout and if no activity is seen even after that the connection is
  # closed.
  #
  # This option is optional. Default value: 20s
  timeout: 20s

  # Usual workers pool configuration
  pool:
    num_workers: 1