version: '3'

services:
  protoc:
    image: zolex/protoc-grpc:0.0.3
    working_dir: /var/www
    volumes:
      - .:/var/www

  server:
    build:
      dockerfile: docker/server/Dockerfile
      context: .
    #command: sh -c "composer dump-autoload && rr serve"
    working_dir: /var/www
    volumes:
      #- ./docker/server/dev/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www
    ports:
      - 3886:3886
    networks:
      - app_network

  client:
    image: zolex/grpc-php-server:0.0.3
    entrypoint: "ash"
    command: -exec "while true; do sleep 1000; done"
    working_dir: /var/www
    volumes:
      - .:/var/www

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3333:3306"
    volumes:
      - ./var/mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: grpc
      MYSQL_DATABASE: grpc
      MYSQL_USER: grpc
      MYSQL_PASSWORD: grpc
    networks:
      - app_network

networks:
  app_network:
    driver: bridge